export const API_ENDPOINTS = {
  AUTH: {
    LOGIN: '/api/v1/auth/login',
    LOGIN_WORKSPACE: '/api/v1/auth/login-workspace',
    LOGOUT: '/api/v1/auth/logout',
    PROFILE: '/api/v1/auth/profile',
    REFRESH: '/api/v1/auth/refresh',
    FORGOT_PASSWORD: '/account/forgotpassword',
    RESET_PASSWORD_WITH_TOKEN: '/account/resetpasswordwithtoken',
    CHANGE_PASSWORD: '/account/resetpassword',
  },
  PROFILE: {
    ME: '/api/v1/profile',
    UPDATE: '/api/v1/profile/Edit',
  },
  AUTHORIZATION: {
    ROLES: '/manageusers/roles',
    ROLE_PERMISSIONS: '/manageusers/rolepermissions',
    SAVE_PERMISSIONS: '/manageusers/saverolepermissions',
  },
  SUPER_ADMIN: {
    GET_TENANTS: '/api/v1/superadmin/tenants',
    GET_DASHBOARD: '/api/v1/superadmin/dashboard',
    GET_INQUIRIES: '/api/v1/superadmin/inquiries',
    GET_INQUIRY_BY_ID: (id: string | number) => `/api/v1/superadmin/inquiries/${id}`,
    UPDATE_INQUIRY_STATUS: (id: string | number) => `/api/v1/superadmin/inquiries/${id}/status`,
  },
  NOTIFICATION: {
    GET_NOTIFICATIONS: '/api/v1/notifications',
    GET_UNREAD_COUNT: '/api/v1/notifications/unread-count',
    MARK_ALL_READ: '/api/v1/notifications/read-all',
    MARK_AS_READ: (notificationId: number | string) => `/api/v1/notifications/${notificationId}/read`,
    API_SAVE_TOKEN: '/api/v1/notifications/save-token',
    API_TEST_NOTIFICATION: '/api/v1/notifications/test-notification',
  },
  TENANTS: {
    BASE: '/api/v1/superadmin/tenants',
    BY_ID: (id: string | number) => `/api/v1/superadmin/tenants/${id}`,
    ACTIVATE: (id: string | number) => `/api/v1/superadmin/tenants/${id}/activate`,
    SUSPEND: (id: string | number) => `/api/v1/superadmin/tenants/${id}/suspend`,
    LOCK: (id: string | number) => `/api/v1/superadmin/tenants/${id}/lock`,
    UNLOCK: (id: string | number) => `/api/v1/superadmin/tenants/${id}/unlock`,
  },
  PLANS: {
    BASE: '/api/v1/superadmin/plans',
    BY_ID: (id: number) => `/api/v1/superadmin/plans/${id}`,
  },
  SUBSCRIPTIONS: {
    BASE: '/api/v1/superadmin/subscriptions',
    BY_ID: (id: number) => `/api/v1/superadmin/subscriptions/${id}`,
    ASSIGN: '/api/v1/superadmin/subscriptions/assign',
  },
  SETTINGS: {
    BASE: '/api/v1/superadmin/settings',
    GET_SETTINGS: '/api/v1/superadmin/settings',
    SAVE_SETTINGS: '/api/v1/superadmin/settings',
  },
  PAYMENT_CONFIG: {
    GET: '/api/v1/superadmin/payment-config',
    SAVE: '/api/v1/superadmin/payment-config',
  },
  LEADS: {
    BASE: '/api/v1/leads',
    SAVE: '/Leads/SaveLead',
    ADD_LEAD: (id?: number | string) => `/api/v1/leads/`,
    ADD_OPTIONS: (id?: number | string) => `/api/v1/leads/form-options`,
    BY_ID: (id: number | string) => `/api/v1/leads/${id}`,
    DETAILS: (id: number | string) => `/api/v1/leads/${id}/details`,

    // Notes
    GET_NOTES: (leadId: number | string) => `/api/v1/leads/${leadId}/notes`,
    ADD_NOTE: (leadId: number | string) => `/api/v1/leads/${leadId}/notes`,
    UPDATE_NOTE: (leadId: number | string, noteId: number | string) => `/api/v1/leads/${leadId}/notes/${noteId}`,
    DELETE_NOTE: (leadId: number | string, noteId: number | string) => `/api/v1/leads/${leadId}/notes/${noteId}`,
    SAVE_NOTE: '/Leads/SaveNote',

    // Follow-ups
    GET_FOLLOW_UPS: (leadId: number | string) => `/api/v1/leads/${leadId}/follow-ups`,
    ADD_FOLLOW_UP: (leadId: number | string) => `/api/v1/leads/${leadId}/follow-ups`,
    EDIT_FOLLOW_UP: (leadId: number | string, followUpId: number | string) => `/api/v1/leads/${leadId}/follow-ups/${followUpId}`,
    DELETE_FOLLOW_UP: (leadId: number | string, followUpId: number | string) => `/api/v1/leads/${leadId}/follow-ups/${followUpId}`,
    SAVE_FOLLOW_UP: '/Leads/SaveFollowUp',

    // Documents / Uploads
    GET_DOCUMENTS: (leadId: number | string) => `/api/v1/leads/${leadId}/documents`,
    UPLOAD_DOC: (leadId: number | string) => `/api/v1/leads/${leadId}/documents`,
    DELETE_DOC: (leadId: number | string, uploadId: number | string) => `/api/v1/leads/${leadId}/documents/${uploadId}`,

    // Site Visits
    GET_SITE_VISITS: (leadId: number | string) => `/api/v1/leads/${leadId}/site-visits`,
    SCHEDULE_SITE_VISIT: (leadId: number | string) => `/api/v1/leads/${leadId}/site-visits`,
    UPDATE_INTEREST_STATUS: (leadId: number | string, followUpId: number | string) => `/api/v1/leads/${leadId}/site-visits/${followUpId}/interest-status`,

    // Activities / Timeline
    GET_ACTIVITIES: (leadId: number | string) => `/api/v1/leads/${leadId}/activities`,
  },
  SALES_PIPELINE: {
    STAGES: '/api/v1/sales-pipeline/stages',
    LEADS_BY_STAGE: '/api/v1/sales-pipeline/leads-by-stage',
    UPDATE_STAGE: '/api/v1/sales-pipeline/update-stage',
  },
  TASKS: {
    GET_TASKS_BY_DATE: (weekStart?: string) =>
      `/Tasks/GetTasksByDate${weekStart ? `?weekStart=${encodeURIComponent(weekStart)}` : ''}`,
    UPDATE_TASK_DATE: '/Tasks/UpdateTaskDate',
    MARK_COMPLETE: '/Tasks/MarkTaskComplete',
    GET_TODAY_NOTIFICATIONS: '/Tasks/GetTodayTaskNotifications',
    MARK_NOTIFICATIONS_READ: '/Tasks/MarkTodayTasksAsRead',
  },
  UNASSIGNED_LEADS: {
    ASSIGN_EXECUTIVE: '/WebhookLeads/AssignExecutive',
    DELETE_LEAD: '/WebhookLeads/DeleteLead',
    GET_UNASSIGNED: '/api/v1/leads',
  },
  PROPERTIES: {
    GET_ALL: '/api/v1/properties',
    GET_LIST: '/api/v1/properties',
    GET_BUILDERS: '/api/v1/properties/builders',
    GET_EXECUTIVES: '/api/v1/properties/executives',
    SAVE: '/api/v1/properties/SaveProperty',
    DELETE: (id: string | number) => `/api/v1/properties/${id}`,
    GET_BY_ID: (id: string | number) => `/api/v1/properties/${id}`,
    BULK_UPLOAD: '/Properties/BulkUpload',
    GET_FLATS: (propertyId: string | number, searchBhk?: string) => `/api/v1/properties/${propertyId}/flats${searchBhk ? `?searchBhk=${searchBhk}` : ''}`,
    SAVE_FLAT: '/api/v1/properties/flats',
    DELETE_FLAT: (flatId: string | number) => `/api/v1/properties/flats/${flatId}`,
    GET_IMAGES: (propertyId: string | number) => `/api/v1/properties/${propertyId}/images`,
    UPLOAD_IMAGE: '/api/v1/properties/UploadImage',
    DELETE_IMAGE: (uploadId?: string | number) => uploadId ? `/api/v1/properties/images/${uploadId}` : '/api/v1/properties/DeleteImage',
    GET_DOCUMENTS: (propertyId: string | number) => `/api/v1/properties/${propertyId}/documents`,
    UPLOAD_DOCUMENT: '/api/v1/properties/UploadDocument',
    DELETE_DOCUMENT: (documentId?: string | number) => documentId ? `/api/v1/properties/documents/${documentId}` : '/api/v1/properties/DeleteDocument',
    DOWNLOAD_DOCUMENT: (documentId: string | number) => `/Properties/DownloadDocument?documentId=${documentId}`,
  },
  QUOTATIONS: {
    GET_QUOATATIONS: '/api/v1/quotations'
  },
  BOOKINGS: {
    BASE: '/api/v1/bookings',
    BY_ID: (id: number | string) => `/api/v1/bookings/${id}`,
    CANCEL: (id: number | string) => `/api/v1/bookings/${id}/cancel`,
  },
  FILES: {
    UPLOAD: '/api/v1/files/upload',
  },
  INVOICES: {
    GET_INVOICE: '/api/v1/invoices',
    BY_ID: (id: number | string) => `/api/v1/invoices/${id}`,
    GENERATE: '/api/v1/invoices/generate',
    DELETE: (id: number | string) => `/api/v1/invoices/${id}`,
    DOWNLOAD_PDF: (id: number | string) => `/api/v1/invoices/${id}/download`,
    SEND: (id: number | string, sendWhatsApp: boolean = true, sendEmail: boolean = false) => `/api/v1/invoices/${id}/send?sendWhatsApp=${sendWhatsApp}&sendEmail=${sendEmail}`,
    RECORD_PAYMENT: (id: number | string) => `/api/v1/invoices/${id}/record-payment`,
  },
  PAYMENTS: {
    BASE: '/api/v1/payments',
    BY_ID: (id: number | string) => `/api/v1/payments/${id}`,
    RECEIPT: (id: number | string) => `/api/v1/payments/${id}/receipt`,
    INVOICE: (id: number | string) => `/api/v1/payments/${id}/invoice`,
    DOWNLOAD: (id: number | string) => `/api/v1/payments/${id}/download`,
  },
  EXPENSES: {
    BASE: '/api/v1/expenses',
    BY_ID: (id: number | string) => `/api/v1/expenses/${id}`,
  },
  AGENTS: {
    BASE: '/api/v1/AgentsApi',
    LIST: '/api/v1/AgentsApi',
    BY_ID: (id: number | string) => `/api/v1/AgentsApi/${id}`,
    GET_AGENT: (agentId: number | string) => `/Agent/GetAgent?id=${agentId}`,
    DETAILS: (id: number | string) => `/Agent/agentdetails/${id}`,
    CHECK_EMAIL: (email: string) => `/Agent/CheckEmailExists?email=${encodeURIComponent(email)}`,
    ONBOARD: '/Agent/Onboard',
    UPDATE: '/Agent/UpdateAgent',
    UPDATE_AGENT: (id?: number | string) => (id ? `/Agent/UpdateAgent?id=${id}` : '/Agent/UpdateAgent'),
    APPROVE: (agentId: number | string) => `/Agent/Approve?agentId=${agentId}`,
    REJECT: (agentId: number | string) => `/Agent/Reject?agentId=${agentId}`,
    DELETE: (agentId: number | string) => `/Agent/Delete?agentId=${agentId}`,
    UPLOAD_DOCUMENT: (agentId: number | string) => `/api/v1/AgentsApi/${agentId}/documents`,
    DELETE_DOCUMENT: (documentId: number | string) => `/api/v1/AgentsApi/documents/${documentId}`,
    DOWNLOAD_DOCUMENT: (documentId: number | string) => `/api/v1/AgentsApi/documents/${documentId}`,
    DOWNLOAD_ALL_DOCUMENTS: (agentId: number | string) => `/api/v1/AgentsApi/${agentId}/documents/download-all`,
    PORTAL_LIST: '/api/p_agents',
    PORTAL_BY_ID: (id: number | string) => `/api/p_agents/${id}`,
    PORTAL_FEATURED: (count: number = 4) => `/api/p_agents/featured?count=${count}`,
  },
  ATTENDANCE: {
    AGENT_OVERVIEW: '/api/v1/attendance/agent-overview',
    CALENDAR: '/api/v1/attendance/calendar',
    INTERVALS: '/api/v1/attendance/intervals',
    LOGIN: '/api/v1/attendance/login',
    LOGOUT: '/api/v1/attendance/logout',
    REQUEST_CORRECTION: '/api/v1/attendance/request-correction',
    APPROVE_CORRECTION: '/api/v1/attendance/approve-correction',
    REJECT_CORRECTION: '/api/v1/attendance/reject-correction',
  },
  PAYOUTS: {
    AGENT: {
      LIST: '/api/v1/agentpayouts',
      DETAILS: (id: number | string) => `/api/v1/agentpayouts/Details/${id}`,
      PROCESS: '/api/v1/agentpayouts/ProcessPayouts',
      UPDATE_STATUS: '/api/v1/agentpayouts/UpdateStatus',
      PAYSLIP: '/api/v1/agentpayouts/Payslip',
    },
    PARTNER: {
      LIST: '/api/v1/channelpartnerpayouts',
      DETAILS: (id: number | string) => `/api/v1/channelpartnerpayouts/Details/${id}`,
      PROCESS: '/api/v1/channelpartnerpayouts/ProcessPayouts',
      UPDATE_STATUS: '/api/v1/channelpartnerpayouts/UpdateStatus',
      RECALCULATE: '/api/v1/channelpartnerpayouts/RecalculatePayouts',
      PAYSLIP: '/api/v1/channelpartnerpayouts/Payslip',
    },
  },
  USER_MANAGEMENT: {
    LIST: '/api/v1/usermanagement',
    CREATE: '/api/v1/usermanagement',
    BY_ID: (id: number | string) => `/api/v1/usermanagement/${id}`,
    IMPERSONATE: (id: number | string) => `/api/v1/usermanagement/Impersonate/${id}`,
    ATTENDANCE: (id: number | string) => `/api/v1/usermanagement/Attendance/${id}`,
  },
  ROLE_MANAGEMENT: {
    LIST: '/api/v1/rolemanagement',
    ADD: '/api/v1/rolemanagement/Add',
    PERMISSIONS: '/api/v1/rolemanagement/Permissions',
  },
  PROFILE_API: {
    GET: '/api/v1/profile',
    EDIT: '/api/v1/profile',
    UPLOAD_AVATAR: '/api/v1/profile/UploadAvatar',
    CHANGE_PASSWORD: '/api/v1/profile/ChangePassword',
  },
  SYSTEM_SETTINGS_API: {
    GET: '/api/v1/systemsettings',
    SAVE: '/api/v1/systemsettings',
    UPLOAD_LOGO: '/api/v1/systemsettings/UploadLogo',
  },
  EMAIL_SETTINGS_API: {
    GET: '/api/v1/emailsettings',
    SAVE_SMTP: '/api/v1/emailsettings/SaveSmtp',
    TEST_EMAIL: '/api/v1/emailsettings/TestEmail',
  },
  PAYMENT_GATEWAY_API: {
    GET: (name: string = 'Razorpay') => `/api/v1/paymentgateways?name=${name}`,
    SAVE: (name: string = 'Razorpay') => `/api/v1/paymentgateways/save?name=${name}`,
  },
  BANK_ACCOUNT_API: {
    LIST: '/api/v1/bankaccounts',
    GET_BY_ID: (id: number | string) => `/api/v1/bankaccounts/${id}`,
    SAVE: '/api/v1/bankaccounts/save',
    DELETE: (id: number | string) => `/api/v1/bankaccounts/${id}`,
  },
  CHATBOT_DASHBOARD_API: {
    GET_DASHBOARD: '/api/v1/chatbotdashboard',
    CONVERSATION_DETAILS: (id: string) => `/api/v1/chatbotdashboard/conversations/${id}`,
    ASSIGN: '/api/v1/chatbotdashboard/assign',
    SEND_MESSAGE: '/api/v1/chatbotdashboard/send-message',
    ANALYTICS: '/api/v1/chatbotdashboard/analytics',
  },
  REWARDS_API: {
    GET_DETAILS: '/api/v1/rewards',
  },
  SUBSCRIPTION_API: {
    PLANS: {
      LIST: '/api/v1/subscriptions/plans',
      DETAILS: (id: number | string) => `/api/v1/subscriptions/plans/${id}`,
      CREATE: '/api/v1/subscriptions/plans/create',
      UPDATE: (id: number | string) => `/api/v1/subscriptions/plans/update/${id}`,
      ACTIVATE: (id: number | string) => `/api/v1/subscriptions/plans/${id}/activate`,
      DEACTIVATE: (id: number | string) => `/api/v1/subscriptions/plans/${id}/deactivate`,
      DELETE: (id: number | string) => `/api/v1/subscriptions/plans/${id}`,
    },
    PARTNER_SUBSCRIPTIONS: {
      LIST: '/api/v1/subscriptions/partner-subscriptions',
      DETAILS: (id: number | string) => `/api/v1/subscriptions/partner-subscriptions/${id}`,
      ASSIGN: '/api/v1/subscriptions/partner-subscriptions/assign',
    },
    RAZORPAY_TRANSACTIONS: {
      LIST: '/api/v1/subscriptions/razorpay-transactions',
      DETAILS: (id: number | string) => `/api/v1/subscriptions/razorpay-transactions/${id}`,
    },
    PENDING_REFUNDS: {
      LIST: '/api/v1/subscriptions/pending-refunds',
      PROCESS: '/api/v1/subscriptions/pending-refunds/process',
    },
    MY_CRM_PLAN: {
      GET: '/api/v1/subscriptions/my-crm-plan',
    },
    CRM_TRANSACTIONS: {
      LIST: '/api/v1/subscriptions/crm-transactions',
      DETAILS: (id: number | string) => `/api/v1/subscriptions/crm-transactions/${id}`,
    },
  },
  TESTIMONIALS: {
    LIST: '/api/v1/settings/testimonials',
    DETAILS: (id: number | string) => `/api/v1/settings/testimonials/${id}`,
    SAVE: '/api/v1/settings/testimonials/save',
    DELETE: (id: number | string) => `/api/v1/settings/testimonials/${id}`,
  },
  DASHBOARD: {
    ANALYTICS: '/api/v1/dashboard',
    RECENT_ACTIVITIES: '/api/v1/dashboard/recent-activities',
    FOLLOW_UPS: '/api/v1/dashboard/follow-ups',
    ADMIN_ANALYTICS: '/api/v1/dashboard/admin',
  },
};